services:
  # Laravel
  laravel:
    image: nadojba/laravel:latest
    container_name: laravel
    networks:
      - laranet

  # MySQL    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laranet
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  # Nginx    
  nginx:
    image: nadojba/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "7000:80"

networks:
  laranet:
    driver: bridge