services:

  laravel:
    image: nadojba/laravel:latest
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: nadojba/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "7000:80"

networks:
  laranet:
    driver: bridge